name: mi_card
description: A new Flutter application.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/tux.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Regular.ttf
        - asset: fonts/Caveat-Bold.ttf

    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Light.ttf
        - asset: fonts/Kalam-Regular.ttf
        - asset: fonts/Kalam-Bold.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf